ALTER TABLE "LotNote"
ADD CONSTRAINT "LotNote_lotId_fkey"
FOREIGN KEY ("lotId") REFERENCES "Lot"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "LotTag"
ADD CONSTRAINT "LotTag_lotId_fkey"
FOREIGN KEY ("lotId") REFERENCES "Lot"("id") ON DELETE CASCADE ON UPDATE CASCADE;